apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-eks
        image: public.ecr.aws/n9m6q4b8/dockerimages:nodejs-pip
        ports:
        - containerPort: 4000
---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
    nodePort: 30004