apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java-eks
        image: public.ecr.aws/n9m6q4b8/dockerimages:java-pip
        ports:
         - containerPort: 8123
---

apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  type: NodePort
  selector:
    app: java
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8123
    nodePort: 30002