apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs
    spec:
      containers:
      - name: reactjs-eks
        image: public.ecr.aws/n9m6q4b8/dockerimages:reactjs-pip
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  type: NodePort
  selector:
    app: reactjs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30003